package com.love.movie.mapper;

import com.love.movie.model.Attitude;
import com.love.movie.model.AttitudeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AttitudeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attitude
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	long countByExample(AttitudeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attitude
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	int deleteByExample(AttitudeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attitude
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	int deleteByPrimaryKey(Integer aid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attitude
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	int insert(Attitude record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attitude
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	int insertSelective(Attitude record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attitude
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	List<Attitude> selectByExample(AttitudeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attitude
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	Attitude selectByPrimaryKey(Integer aid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attitude
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Attitude record, @Param("example") AttitudeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attitude
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	int updateByExample(@Param("record") Attitude record, @Param("example") AttitudeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attitude
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	int updateByPrimaryKeySelective(Attitude record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attitude
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	int updateByPrimaryKey(Attitude record);
}