package com.love.movie.mapper;

import com.love.movie.model.Comment;
import com.love.movie.model.CommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbg.generated  Wed Jun 26 10:52:09 CST 2019
	 */
	long countByExample(CommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbg.generated  Wed Jun 26 10:52:09 CST 2019
	 */
	int deleteByExample(CommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbg.generated  Wed Jun 26 10:52:09 CST 2019
	 */
	int deleteByPrimaryKey(Integer cid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbg.generated  Wed Jun 26 10:52:09 CST 2019
	 */
	int insert(Comment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbg.generated  Wed Jun 26 10:52:09 CST 2019
	 */
	int insertSelective(Comment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbg.generated  Wed Jun 26 10:52:09 CST 2019
	 */
	List<Comment> selectByExampleWithBLOBs(CommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbg.generated  Wed Jun 26 10:52:09 CST 2019
	 */
	List<Comment> selectByExample(CommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbg.generated  Wed Jun 26 10:52:09 CST 2019
	 */
	Comment selectByPrimaryKey(Integer cid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbg.generated  Wed Jun 26 10:52:09 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Comment record, @Param("example") CommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbg.generated  Wed Jun 26 10:52:09 CST 2019
	 */
	int updateByExampleWithBLOBs(@Param("record") Comment record, @Param("example") CommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbg.generated  Wed Jun 26 10:52:09 CST 2019
	 */
	int updateByExample(@Param("record") Comment record, @Param("example") CommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbg.generated  Wed Jun 26 10:52:09 CST 2019
	 */
	int updateByPrimaryKeySelective(Comment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbg.generated  Wed Jun 26 10:52:09 CST 2019
	 */
	int updateByPrimaryKeyWithBLOBs(Comment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbg.generated  Wed Jun 26 10:52:09 CST 2019
	 */
	int updateByPrimaryKey(Comment record);
}