package com.love.movie.mapper;

import com.love.movie.model.FolloweeExample;
import com.love.movie.model.FolloweeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FolloweeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table followee
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    long countByExample(FolloweeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table followee
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    int deleteByExample(FolloweeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table followee
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    int deleteByPrimaryKey(FolloweeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table followee
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    int insert(FolloweeKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table followee
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    int insertSelective(FolloweeKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table followee
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    List<FolloweeKey> selectByExample(FolloweeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table followee
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") FolloweeKey record, @Param("example") FolloweeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table followee
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    int updateByExample(@Param("record") FolloweeKey record, @Param("example") FolloweeExample example);
}