package com.love.movie.mapper;

import com.love.movie.model.FollowerExample;
import com.love.movie.model.FollowerKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FollowerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table follower
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	long countByExample(FollowerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table follower
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	int deleteByExample(FollowerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table follower
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	int deleteByPrimaryKey(FollowerKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table follower
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	int insert(FollowerKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table follower
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	int insertSelective(FollowerKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table follower
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	List<FollowerKey> selectByExample(FollowerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table follower
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	int updateByExampleSelective(@Param("record") FollowerKey record, @Param("example") FollowerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table follower
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	int updateByExample(@Param("record") FollowerKey record, @Param("example") FollowerExample example);
}