package com.love.movie.mapper;

import com.love.movie.model.Report;
import com.love.movie.model.ReportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReportMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table report
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	long countByExample(ReportExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table report
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	int deleteByExample(ReportExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table report
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	int deleteByPrimaryKey(Integer reportid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table report
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	int insert(Report record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table report
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	int insertSelective(Report record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table report
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	List<Report> selectByExample(ReportExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table report
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	Report selectByPrimaryKey(Integer reportid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table report
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Report record, @Param("example") ReportExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table report
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	int updateByExample(@Param("record") Report record, @Param("example") ReportExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table report
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	int updateByPrimaryKeySelective(Report record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table report
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	int updateByPrimaryKey(Report record);
}