package com.love.movie.mapper;

import com.love.movie.model.Seenmovie;
import com.love.movie.model.SeenmovieExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SeenmovieMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table seenmovie
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	long countByExample(SeenmovieExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table seenmovie
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	int deleteByExample(SeenmovieExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table seenmovie
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	int deleteByPrimaryKey(Integer seenmid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table seenmovie
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	int insert(Seenmovie record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table seenmovie
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	int insertSelective(Seenmovie record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table seenmovie
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	List<Seenmovie> selectByExample(SeenmovieExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table seenmovie
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	Seenmovie selectByPrimaryKey(Integer seenmid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table seenmovie
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Seenmovie record, @Param("example") SeenmovieExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table seenmovie
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	int updateByExample(@Param("record") Seenmovie record, @Param("example") SeenmovieExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table seenmovie
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	int updateByPrimaryKeySelective(Seenmovie record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table seenmovie
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	int updateByPrimaryKey(Seenmovie record);
}