package com.love.movie.mapper;

import com.love.movie.model.Wseemovie;
import com.love.movie.model.WseemovieExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WseemovieMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wseemovie
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	long countByExample(WseemovieExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wseemovie
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	int deleteByExample(WseemovieExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wseemovie
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	int deleteByPrimaryKey(Integer wseemid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wseemovie
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	int insert(Wseemovie record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wseemovie
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	int insertSelective(Wseemovie record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wseemovie
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	List<Wseemovie> selectByExample(WseemovieExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wseemovie
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	Wseemovie selectByPrimaryKey(Integer wseemid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wseemovie
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Wseemovie record, @Param("example") WseemovieExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wseemovie
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	int updateByExample(@Param("record") Wseemovie record, @Param("example") WseemovieExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wseemovie
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	int updateByPrimaryKeySelective(Wseemovie record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wseemovie
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	int updateByPrimaryKey(Wseemovie record);
}