package com.love.movie.model;

public class Attitude {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attitude.aid
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	private Integer aid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attitude.uid
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attitude.cid
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	private Integer cid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attitude.attitude
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	private Integer attitude;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attitude.aid
	 * @return  the value of attitude.aid
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	public Integer getAid() {
		return aid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attitude.aid
	 * @param aid  the value for attitude.aid
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	public void setAid(Integer aid) {
		this.aid = aid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attitude.uid
	 * @return  the value of attitude.uid
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attitude.uid
	 * @param uid  the value for attitude.uid
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attitude.cid
	 * @return  the value of attitude.cid
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	public Integer getCid() {
		return cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attitude.cid
	 * @param cid  the value for attitude.cid
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	public void setCid(Integer cid) {
		this.cid = cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attitude.attitude
	 * @return  the value of attitude.attitude
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	public Integer getAttitude() {
		return attitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attitude.attitude
	 * @param attitude  the value for attitude.attitude
	 * @mbg.generated  Sun Jun 30 13:44:07 CST 2019
	 */
	public void setAttitude(Integer attitude) {
		this.attitude = attitude;
	}
}