package com.love.movie.model;

import java.util.Date;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.cid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.uid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.mid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private Integer mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.cdate
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private Date cdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.clike
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private Integer clike;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.report
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private Integer report;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.cid
     *
     * @return the value of comment.cid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.cid
     *
     * @param cid the value for comment.cid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.uid
     *
     * @return the value of comment.uid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.uid
     *
     * @param uid the value for comment.uid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.mid
     *
     * @return the value of comment.mid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.mid
     *
     * @param mid the value for comment.mid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.cdate
     *
     * @return the value of comment.cdate
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public Date getCdate() {
        return cdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.cdate
     *
     * @param cdate the value for comment.cdate
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setCdate(Date cdate) {
        this.cdate = cdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.clike
     *
     * @return the value of comment.clike
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public Integer getClike() {
        return clike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.clike
     *
     * @param clike the value for comment.clike
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setClike(Integer clike) {
        this.clike = clike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.report
     *
     * @return the value of comment.report
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public Integer getReport() {
        return report;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.report
     *
     * @param report the value for comment.report
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setReport(Integer report) {
        this.report = report;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }
}