package com.love.movie.model;

public class FollowerKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column follower.uid
	 * @mbg.generated  Fri Jun 21 16:04:53 CST 2019
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column follower.fer_uid
	 * @mbg.generated  Fri Jun 21 16:04:53 CST 2019
	 */
	private Integer ferUid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column follower.uid
	 * @return  the value of follower.uid
	 * @mbg.generated  Fri Jun 21 16:04:53 CST 2019
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column follower.uid
	 * @param uid  the value for follower.uid
	 * @mbg.generated  Fri Jun 21 16:04:53 CST 2019
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column follower.fer_uid
	 * @return  the value of follower.fer_uid
	 * @mbg.generated  Fri Jun 21 16:04:53 CST 2019
	 */
	public Integer getFerUid() {
		return ferUid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column follower.fer_uid
	 * @param ferUid  the value for follower.fer_uid
	 * @mbg.generated  Fri Jun 21 16:04:53 CST 2019
	 */
	public void setFerUid(Integer ferUid) {
		this.ferUid = ferUid;
	}
}