package com.love.movie.model;

public class FollwerKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column follwer.uid
	 * @mbg.generated  Mon Jun 24 11:18:24 CST 2019
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column follwer.use_uid
	 * @mbg.generated  Mon Jun 24 11:18:24 CST 2019
	 */
	private Integer useUid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column follwer.uid
	 * @return  the value of follwer.uid
	 * @mbg.generated  Mon Jun 24 11:18:24 CST 2019
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column follwer.uid
	 * @param uid  the value for follwer.uid
	 * @mbg.generated  Mon Jun 24 11:18:24 CST 2019
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column follwer.use_uid
	 * @return  the value of follwer.use_uid
	 * @mbg.generated  Mon Jun 24 11:18:24 CST 2019
	 */
	public Integer getUseUid() {
		return useUid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column follwer.use_uid
	 * @param useUid  the value for follwer.use_uid
	 * @mbg.generated  Mon Jun 24 11:18:24 CST 2019
	 */
	public void setUseUid(Integer useUid) {
		this.useUid = useUid;
	}
}