package com.love.movie.model;

public class FolloweeKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column followee.uid
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column followee.use_uid
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	private Integer useUid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column followee.uid
	 * @return  the value of followee.uid
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column followee.uid
	 * @param uid  the value for followee.uid
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column followee.use_uid
	 * @return  the value of followee.use_uid
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	public Integer getUseUid() {
		return useUid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column followee.use_uid
	 * @param useUid  the value for followee.use_uid
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	public void setUseUid(Integer useUid) {
		this.useUid = useUid;
	}
}