package com.love.movie.model;

public class Level {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column level.lid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private Integer lid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column level.lname
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private String lname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column level.lid
     *
     * @return the value of level.lid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public Integer getLid() {
        return lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column level.lid
     *
     * @param lid the value for level.lid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setLid(Integer lid) {
        this.lid = lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column level.lname
     *
     * @return the value of level.lname
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public String getLname() {
        return lname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column level.lname
     *
     * @param lname the value for level.lname
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setLname(String lname) {
        this.lname = lname;
    }
}