package com.love.movie.model;

import java.util.Date;

public class Movie {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.mid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private Integer mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.mname
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private String mname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.mtag
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private Integer mtag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.mscore
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private Float mscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.murl
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private String murl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.mcount
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private Integer mcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.mdirect
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private String mdirect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.mwriter
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private String mwriter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.mactor
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private String mactor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.mcountry
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private String mcountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.mlanguage
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private String mlanguage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.mtime
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private Date mtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.malias
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private String malias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.mrelease
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private Integer mrelease;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.mbrief
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private String mbrief;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.mid
     *
     * @return the value of movie.mid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.mid
     *
     * @param mid the value for movie.mid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.mname
     *
     * @return the value of movie.mname
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public String getMname() {
        return mname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.mname
     *
     * @param mname the value for movie.mname
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setMname(String mname) {
        this.mname = mname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.mtag
     *
     * @return the value of movie.mtag
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public Integer getMtag() {
        return mtag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.mtag
     *
     * @param mtag the value for movie.mtag
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setMtag(Integer mtag) {
        this.mtag = mtag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.mscore
     *
     * @return the value of movie.mscore
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public Float getMscore() {
        return mscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.mscore
     *
     * @param mscore the value for movie.mscore
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setMscore(Float mscore) {
        this.mscore = mscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.murl
     *
     * @return the value of movie.murl
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public String getMurl() {
        return murl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.murl
     *
     * @param murl the value for movie.murl
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setMurl(String murl) {
        this.murl = murl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.mcount
     *
     * @return the value of movie.mcount
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public Integer getMcount() {
        return mcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.mcount
     *
     * @param mcount the value for movie.mcount
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setMcount(Integer mcount) {
        this.mcount = mcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.mdirect
     *
     * @return the value of movie.mdirect
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public String getMdirect() {
        return mdirect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.mdirect
     *
     * @param mdirect the value for movie.mdirect
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setMdirect(String mdirect) {
        this.mdirect = mdirect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.mwriter
     *
     * @return the value of movie.mwriter
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public String getMwriter() {
        return mwriter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.mwriter
     *
     * @param mwriter the value for movie.mwriter
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setMwriter(String mwriter) {
        this.mwriter = mwriter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.mactor
     *
     * @return the value of movie.mactor
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public String getMactor() {
        return mactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.mactor
     *
     * @param mactor the value for movie.mactor
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setMactor(String mactor) {
        this.mactor = mactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.mcountry
     *
     * @return the value of movie.mcountry
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public String getMcountry() {
        return mcountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.mcountry
     *
     * @param mcountry the value for movie.mcountry
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setMcountry(String mcountry) {
        this.mcountry = mcountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.mlanguage
     *
     * @return the value of movie.mlanguage
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public String getMlanguage() {
        return mlanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.mlanguage
     *
     * @param mlanguage the value for movie.mlanguage
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setMlanguage(String mlanguage) {
        this.mlanguage = mlanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.mtime
     *
     * @return the value of movie.mtime
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.mtime
     *
     * @param mtime the value for movie.mtime
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.malias
     *
     * @return the value of movie.malias
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public String getMalias() {
        return malias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.malias
     *
     * @param malias the value for movie.malias
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setMalias(String malias) {
        this.malias = malias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.mrelease
     *
     * @return the value of movie.mrelease
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public Integer getMrelease() {
        return mrelease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.mrelease
     *
     * @param mrelease the value for movie.mrelease
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setMrelease(Integer mrelease) {
        this.mrelease = mrelease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.mbrief
     *
     * @return the value of movie.mbrief
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public String getMbrief() {
        return mbrief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.mbrief
     *
     * @param mbrief the value for movie.mbrief
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setMbrief(String mbrief) {
        this.mbrief = mbrief;
    }
}