package com.love.movie.model;

public class Reply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.rid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.cid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.replyid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private Integer replyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.replytype
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private Integer replytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.uid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.touid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private Integer touid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.rcontent
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private String rcontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.rid
     *
     * @return the value of reply.rid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.rid
     *
     * @param rid the value for reply.rid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.cid
     *
     * @return the value of reply.cid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.cid
     *
     * @param cid the value for reply.cid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.replyid
     *
     * @return the value of reply.replyid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public Integer getReplyid() {
        return replyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.replyid
     *
     * @param replyid the value for reply.replyid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setReplyid(Integer replyid) {
        this.replyid = replyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.replytype
     *
     * @return the value of reply.replytype
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public Integer getReplytype() {
        return replytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.replytype
     *
     * @param replytype the value for reply.replytype
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setReplytype(Integer replytype) {
        this.replytype = replytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.uid
     *
     * @return the value of reply.uid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.uid
     *
     * @param uid the value for reply.uid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.touid
     *
     * @return the value of reply.touid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public Integer getTouid() {
        return touid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.touid
     *
     * @param touid the value for reply.touid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setTouid(Integer touid) {
        this.touid = touid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.rcontent
     *
     * @return the value of reply.rcontent
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public String getRcontent() {
        return rcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.rcontent
     *
     * @param rcontent the value for reply.rcontent
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setRcontent(String rcontent) {
        this.rcontent = rcontent;
    }
}