package com.love.movie.model;

import java.util.Date;

public class Report {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column report.reportid
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	private Integer reportid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column report.cid
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	private Integer cid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column report.uid
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column report.reportdate
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	private Date reportdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column report.reason
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	private String reason;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column report.reportid
	 * @return  the value of report.reportid
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	public Integer getReportid() {
		return reportid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column report.reportid
	 * @param reportid  the value for report.reportid
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	public void setReportid(Integer reportid) {
		this.reportid = reportid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column report.cid
	 * @return  the value of report.cid
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	public Integer getCid() {
		return cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column report.cid
	 * @param cid  the value for report.cid
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	public void setCid(Integer cid) {
		this.cid = cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column report.uid
	 * @return  the value of report.uid
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column report.uid
	 * @param uid  the value for report.uid
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column report.reportdate
	 * @return  the value of report.reportdate
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	public Date getReportdate() {
		return reportdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column report.reportdate
	 * @param reportdate  the value for report.reportdate
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	public void setReportdate(Date reportdate) {
		this.reportdate = reportdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column report.reason
	 * @return  the value of report.reason
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	public String getReason() {
		return reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column report.reason
	 * @param reason  the value for report.reason
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	public void setReason(String reason) {
		this.reason = reason;
	}
}