package com.love.movie.model;

public class Seenmovie {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column seenmovie.seenmid
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	private Integer seenmid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column seenmovie.uid
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column seenmovie.mid
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	private Integer mid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column seenmovie.seenmid
	 * @return  the value of seenmovie.seenmid
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	public Integer getSeenmid() {
		return seenmid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column seenmovie.seenmid
	 * @param seenmid  the value for seenmovie.seenmid
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	public void setSeenmid(Integer seenmid) {
		this.seenmid = seenmid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column seenmovie.uid
	 * @return  the value of seenmovie.uid
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column seenmovie.uid
	 * @param uid  the value for seenmovie.uid
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column seenmovie.mid
	 * @return  the value of seenmovie.mid
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	public Integer getMid() {
		return mid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column seenmovie.mid
	 * @param mid  the value for seenmovie.mid
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	public void setMid(Integer mid) {
		this.mid = mid;
	}
}