package com.love.movie.model;

import java.util.Date;

public class Storeup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storeup.sid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storeup.uid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storeup.cid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storeup.sdate
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    private Date sdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storeup.sid
     *
     * @return the value of storeup.sid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storeup.sid
     *
     * @param sid the value for storeup.sid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storeup.uid
     *
     * @return the value of storeup.uid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storeup.uid
     *
     * @param uid the value for storeup.uid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storeup.cid
     *
     * @return the value of storeup.cid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storeup.cid
     *
     * @param cid the value for storeup.cid
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storeup.sdate
     *
     * @return the value of storeup.sdate
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public Date getSdate() {
        return sdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storeup.sdate
     *
     * @param sdate the value for storeup.sdate
     *
     * @mbg.generated Wed Jun 19 18:53:06 CST 2019
     */
    public void setSdate(Date sdate) {
        this.sdate = sdate;
    }
}