package com.love.movie.model;

import java.util.Date;

public class Storeup {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column storeup.storeid
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	private Integer storeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column storeup.uid
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column storeup.cid
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	private Integer cid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column storeup.storedate
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	private Date storedate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column storeup.storeid
	 * @return  the value of storeup.storeid
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	public Integer getStoreid() {
		return storeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column storeup.storeid
	 * @param storeid  the value for storeup.storeid
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	public void setStoreid(Integer storeid) {
		this.storeid = storeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column storeup.uid
	 * @return  the value of storeup.uid
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column storeup.uid
	 * @param uid  the value for storeup.uid
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column storeup.cid
	 * @return  the value of storeup.cid
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	public Integer getCid() {
		return cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column storeup.cid
	 * @param cid  the value for storeup.cid
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	public void setCid(Integer cid) {
		this.cid = cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column storeup.storedate
	 * @return  the value of storeup.storedate
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	public Date getStoredate() {
		return storedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column storeup.storedate
	 * @param storedate  the value for storeup.storedate
	 * @mbg.generated  Sun Jun 30 00:37:38 CST 2019
	 */
	public void setStoredate(Date storedate) {
		this.storedate = storedate;
	}
}