package com.love.movie.model;

public class TopiccomentsKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topiccoments.uid
	 * @mbg.generated  Thu Jun 27 10:59:16 CST 2019
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topiccoments.tid
	 * @mbg.generated  Thu Jun 27 10:59:16 CST 2019
	 */
	private Integer tid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topiccoments.uid
	 * @return  the value of topiccoments.uid
	 * @mbg.generated  Thu Jun 27 10:59:16 CST 2019
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topiccoments.uid
	 * @param uid  the value for topiccoments.uid
	 * @mbg.generated  Thu Jun 27 10:59:16 CST 2019
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topiccoments.tid
	 * @return  the value of topiccoments.tid
	 * @mbg.generated  Thu Jun 27 10:59:16 CST 2019
	 */
	public Integer getTid() {
		return tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topiccoments.tid
	 * @param tid  the value for topiccoments.tid
	 * @mbg.generated  Thu Jun 27 10:59:16 CST 2019
	 */
	public void setTid(Integer tid) {
		this.tid = tid;
	}
}