package com.love.movie.model;

import java.util.Date;

public class Topic {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topic.tid
	 * @mbg.generated  Thu Jun 27 10:59:16 CST 2019
	 */
	private Integer tid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topic.uid
	 * @mbg.generated  Thu Jun 27 10:59:16 CST 2019
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topic.tname
	 * @mbg.generated  Thu Jun 27 10:59:16 CST 2019
	 */
	private String tname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topic.tcreateuser
	 * @mbg.generated  Thu Jun 27 10:59:16 CST 2019
	 */
	private Integer tcreateuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topic.tdate
	 * @mbg.generated  Thu Jun 27 10:59:16 CST 2019
	 */
	private Date tdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topic.tfollower
	 * @mbg.generated  Thu Jun 27 10:59:16 CST 2019
	 */
	private Integer tfollower;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topic.tcontent
	 * @mbg.generated  Thu Jun 27 10:59:16 CST 2019
	 */
	private String tcontent;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topic.tid
	 * @return  the value of topic.tid
	 * @mbg.generated  Thu Jun 27 10:59:16 CST 2019
	 */
	public Integer getTid() {
		return tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topic.tid
	 * @param tid  the value for topic.tid
	 * @mbg.generated  Thu Jun 27 10:59:16 CST 2019
	 */
	public void setTid(Integer tid) {
		this.tid = tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topic.uid
	 * @return  the value of topic.uid
	 * @mbg.generated  Thu Jun 27 10:59:16 CST 2019
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topic.uid
	 * @param uid  the value for topic.uid
	 * @mbg.generated  Thu Jun 27 10:59:16 CST 2019
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topic.tname
	 * @return  the value of topic.tname
	 * @mbg.generated  Thu Jun 27 10:59:16 CST 2019
	 */
	public String getTname() {
		return tname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topic.tname
	 * @param tname  the value for topic.tname
	 * @mbg.generated  Thu Jun 27 10:59:16 CST 2019
	 */
	public void setTname(String tname) {
		this.tname = tname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topic.tcreateuser
	 * @return  the value of topic.tcreateuser
	 * @mbg.generated  Thu Jun 27 10:59:16 CST 2019
	 */
	public Integer getTcreateuser() {
		return tcreateuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topic.tcreateuser
	 * @param tcreateuser  the value for topic.tcreateuser
	 * @mbg.generated  Thu Jun 27 10:59:16 CST 2019
	 */
	public void setTcreateuser(Integer tcreateuser) {
		this.tcreateuser = tcreateuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topic.tdate
	 * @return  the value of topic.tdate
	 * @mbg.generated  Thu Jun 27 10:59:16 CST 2019
	 */
	public Date getTdate() {
		return tdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topic.tdate
	 * @param tdate  the value for topic.tdate
	 * @mbg.generated  Thu Jun 27 10:59:16 CST 2019
	 */
	public void setTdate(Date tdate) {
		this.tdate = tdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topic.tfollower
	 * @return  the value of topic.tfollower
	 * @mbg.generated  Thu Jun 27 10:59:16 CST 2019
	 */
	public Integer getTfollower() {
		return tfollower;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topic.tfollower
	 * @param tfollower  the value for topic.tfollower
	 * @mbg.generated  Thu Jun 27 10:59:16 CST 2019
	 */
	public void setTfollower(Integer tfollower) {
		this.tfollower = tfollower;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topic.tcontent
	 * @return  the value of topic.tcontent
	 * @mbg.generated  Thu Jun 27 10:59:16 CST 2019
	 */
	public String getTcontent() {
		return tcontent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topic.tcontent
	 * @param tcontent  the value for topic.tcontent
	 * @mbg.generated  Thu Jun 27 10:59:16 CST 2019
	 */
	public void setTcontent(String tcontent) {
		this.tcontent = tcontent;
	}
}