package com.love.movie.model;

public class UlevelKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ulevel.uid
	 * @mbg.generated  Wed Jun 26 10:52:09 CST 2019
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ulevel.lid
	 * @mbg.generated  Wed Jun 26 10:52:09 CST 2019
	 */
	private Integer lid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ulevel.uid
	 * @return  the value of ulevel.uid
	 * @mbg.generated  Wed Jun 26 10:52:09 CST 2019
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ulevel.uid
	 * @param uid  the value for ulevel.uid
	 * @mbg.generated  Wed Jun 26 10:52:09 CST 2019
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ulevel.lid
	 * @return  the value of ulevel.lid
	 * @mbg.generated  Wed Jun 26 10:52:09 CST 2019
	 */
	public Integer getLid() {
		return lid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ulevel.lid
	 * @param lid  the value for ulevel.lid
	 * @mbg.generated  Wed Jun 26 10:52:09 CST 2019
	 */
	public void setLid(Integer lid) {
		this.lid = lid;
	}
}