package com.love.movie.model;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.uid
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.username
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.email
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.gender
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	private Integer gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.birth
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	private Date birth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.brief
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	private String brief;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.udate
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	private Date udate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.telephone
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	private String telephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.level
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	private Integer level;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.uimg
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	private String uimg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.uid
	 * @return  the value of user.uid
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.uid
	 * @param uid  the value for user.uid
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.username
	 * @return  the value of user.username
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.username
	 * @param username  the value for user.username
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.email
	 * @return  the value of user.email
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.email
	 * @param email  the value for user.email
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.gender
	 * @return  the value of user.gender
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	public Integer getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.gender
	 * @param gender  the value for user.gender
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	public void setGender(Integer gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.birth
	 * @return  the value of user.birth
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	public Date getBirth() {
		return birth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.birth
	 * @param birth  the value for user.birth
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	public void setBirth(Date birth) {
		this.birth = birth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.brief
	 * @return  the value of user.brief
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	public String getBrief() {
		return brief;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.brief
	 * @param brief  the value for user.brief
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	public void setBrief(String brief) {
		this.brief = brief;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.udate
	 * @return  the value of user.udate
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	public Date getUdate() {
		return udate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.udate
	 * @param udate  the value for user.udate
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	public void setUdate(Date udate) {
		this.udate = udate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.telephone
	 * @return  the value of user.telephone
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.telephone
	 * @param telephone  the value for user.telephone
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.level
	 * @return  the value of user.level
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	public Integer getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.level
	 * @param level  the value for user.level
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	public void setLevel(Integer level) {
		this.level = level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.uimg
	 * @return  the value of user.uimg
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	public String getUimg() {
		return uimg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.uimg
	 * @param uimg  the value for user.uimg
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	public void setUimg(String uimg) {
		this.uimg = uimg;
	}

	@Override
	public String toString() {
		return "User [uid=" + uid + ", username=" + username + ", password=" + password + ", email=" + email
				+ ", gender=" + gender + ", birth=" + birth + ", brief=" + brief + ", udate=" + udate + ", telephone="
				+ telephone + ", level=" + level + ", uimg=" + uimg + "]";
	}

	
}