package com.love.movie.model;

public class Wseemovie {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wseemovie.wseemid
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	private Integer wseemid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wseemovie.uid
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wseemovie.mid
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	private Integer mid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wseemovie.wseemid
	 * @return  the value of wseemovie.wseemid
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	public Integer getWseemid() {
		return wseemid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wseemovie.wseemid
	 * @param wseemid  the value for wseemovie.wseemid
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	public void setWseemid(Integer wseemid) {
		this.wseemid = wseemid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wseemovie.uid
	 * @return  the value of wseemovie.uid
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wseemovie.uid
	 * @param uid  the value for wseemovie.uid
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wseemovie.mid
	 * @return  the value of wseemovie.mid
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	public Integer getMid() {
		return mid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wseemovie.mid
	 * @param mid  the value for wseemovie.mid
	 * @mbg.generated  Mon Jun 24 19:49:52 CST 2019
	 */
	public void setMid(Integer mid) {
		this.mid = mid;
	}
}