package com.love.movie.model;

public class Wseenmovie {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wseenmovie.wseenmid
     *
     * @mbg.generated Mon Jun 24 19:35:52 CST 2019
     */
    private Integer wseenmid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wseenmovie.uid
     *
     * @mbg.generated Mon Jun 24 19:35:52 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wseenmovie.mid
     *
     * @mbg.generated Mon Jun 24 19:35:52 CST 2019
     */
    private Integer mid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wseenmovie.wseenmid
     *
     * @return the value of wseenmovie.wseenmid
     *
     * @mbg.generated Mon Jun 24 19:35:52 CST 2019
     */
    public Integer getWseenmid() {
        return wseenmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wseenmovie.wseenmid
     *
     * @param wseenmid the value for wseenmovie.wseenmid
     *
     * @mbg.generated Mon Jun 24 19:35:52 CST 2019
     */
    public void setWseenmid(Integer wseenmid) {
        this.wseenmid = wseenmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wseenmovie.uid
     *
     * @return the value of wseenmovie.uid
     *
     * @mbg.generated Mon Jun 24 19:35:52 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wseenmovie.uid
     *
     * @param uid the value for wseenmovie.uid
     *
     * @mbg.generated Mon Jun 24 19:35:52 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wseenmovie.mid
     *
     * @return the value of wseenmovie.mid
     *
     * @mbg.generated Mon Jun 24 19:35:52 CST 2019
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wseenmovie.mid
     *
     * @param mid the value for wseenmovie.mid
     *
     * @mbg.generated Mon Jun 24 19:35:52 CST 2019
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }
}